### ISSUE TITLE
having issues with youcompleteme

### ISSUE THREAD

**Issue by SolarAquarion** [atweiden/pkgbuilds-plugged#1]
Found clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  -> Found clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz.sig
==> ERROR: Integrity checks (sha256) differ in size from the source array.

**Comment by atweiden** [comment]
Can you copy/paste the PKGBUILD here?

**Comment by SolarAquarion** [comment]
https://github.com/atweiden/pkgbuilds-plugged/tree/master/vim-youcompleteme-plugged-git

It's the one from here.

**Comment by atweiden** [comment]
Makepkg will throw this error when there are fewer sha256sums in the PKGBUILD than there are items in the source array.

Did you intend to build plugged PKGBUILDs? I've built the latest ycm from the PKGBUILD in the pkgbuilds-plugged repo on x86_64 as of today without issues.

**Comment by SolarAquarion** [comment]
Yes, but I guess but all the sha526sums should be matching I even did
updpkgsums and it didn't work

**Comment by atweiden** [comment]
`updpkgsums` messes up the sha256sums. Redownload the PKGBUILD and try again.

**Comment by SolarAquarion** [comment]
it works now
